name: Ruby CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "3.1"
          bundler-cache: true # Caches gems for faster runs
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec ruby test_hello.rb
      - name: Run RuboCop
        run: bundle exec rubocop